const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const data = {};
const sent = [];
let failure = 0;
const props = {getProperty:k=>data[k]??null, setProperty:(k,v)=>{assert(Buffer.byteLength(v)<9000);data[k]=v;}, deleteProperty:k=>delete data[k]};
const context = vm.createContext({console, PropertiesService:{getScriptProperties:()=>props}, LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})}, Utilities:{base64Encode:s=>Buffer.from(s).toString('base64'),getUuid:()=>String(Math.random()),formatDate:()=> '2026-09-29'}, ScriptApp:{getService:()=>({getUrl:()=> 'https://example.test/exec'})}, UrlFetchApp:{fetch:(url,opts)=>{sent.push(opts.payload);return {getResponseCode:()=>failure?400:201,getContentText:()=>JSON.stringify(failure?{code:failure}:{sid:'SMtest',status:'queued'})}}}});
vm.runInContext(fs.readFileSync(__dirname+'/Code.gs','utf8'), context);
assert.throws(()=>context.subscribe_({name:'Test Owner',phone:'5551234567',consent:'yes'}),/not available/);
Object.assign(data,{TWILIO_ACCOUNT_SID:'test',TWILIO_AUTH_TOKEN:'test',TWILIO_FROM_NUMBER:'+15550000000'});
assert.throws(()=>context.subscribe_({name:'Test Owner',phone:'5551234567'}),/Consent/);
context.subscribe_({name:'Test Owner',phone:'5551234567',consent:'yes'});
assert.equal(context.loadSubscribers_()[0].status,'active');
assert.match(sent[0].Body,/STOP/);
assert.equal(context.loadSubscribers_().length,1);
const outbox=[{id:'test',phone:'+15551234567',body:'Weather test',attempts:0}];
failure=30003;
assert.equal(context.drainOutbox_(outbox).pending,1);
failure=0;
assert.equal(context.drainOutbox_(JSON.parse(context.readLargeProperty_('spa_schedule_outbox_v1'))).accepted,1);
assert.equal(JSON.parse(context.readLargeProperty_('spa_schedule_outbox_v1')).length,0);
failure=21610;
context.drainOutbox_(outbox);
assert.equal(context.loadSubscribers_()[0].status,'opted_out');
assert.throws(()=>context.subscribe_({name:'Test Owner',phone:'5551234567',consent:'yes'}),/START/);
assert.equal(context.loadSubscribers_()[0].status,'opted_out');
failure=0;
context.subscribe_({name:'Test Owner',phone:'5551234567',consent:'yes'});
assert.equal(context.loadSubscribers_()[0].status,'active');
data.WEATHER_ALERT_TEXT='Practice canceled. Stay home.';
assert.equal(context.previewWeatherAlert().recipients,1);
assert.throws(()=>context.sendApprovedWeatherAlert(),/approved text/);
data.WEATHER_ALERT_APPROVED_TEXT=data.WEATHER_ALERT_TEXT;
assert.equal(context.sendApprovedWeatherAlert().accepted,1);
assert.equal(data.WEATHER_ALERT_APPROVED_TEXT,undefined);
assert.throws(()=>context.sendApprovedWeatherAlert(),/approved text/);
const large='😀'.repeat(15000);
context.writeLargeProperty_('large',large);
assert.equal(context.readLargeProperty_('large'),large);
context.writeLargeProperty_('large','small');
assert.equal(context.readLargeProperty_('large'),'small');
assert.equal(data.large_part_2,undefined);
console.log('PASS: consent, configuration guard, signup, retry, STOP suppression, START rejoin, owner approval, one-time send, chunked storage.');
const event={key:'2026-09-30|practice||',date:'2026-09-30',category:'Practice',title:'Practice',startTime:'4 PM',endTime:'5 PM',notes:'',location:'Field'};
context.saveSnapshot_([event]);
context.loadScheduleEvents_=()=>[{...event,location:'Gym'}];
failure=30003;
assert.equal(context.checkForScheduleChanges().pending,1);
failure=0;
assert.equal(context.checkForScheduleChanges().accepted,1);
assert.equal(context.checkForScheduleChanges().accepted,0);
context.loadScheduleEvents_=()=>[];
assert.throws(()=>context.checkForScheduleChanges(),/Empty schedule/);
assert.equal(context.loadSnapshot_().length,1);
console.log('PASS: schedule change retries without requeue, no duplicate on next poll, empty CSV preserves snapshot.');
